name: Build and Deploy to Firebase
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./FitMind
        # Toto stiahne všetky knižnice potrebné pre build
        run: npm install

      - name: Build Angular
        working-directory: ./FitMind
        # Spustíme build cez npx, aby sme mali istotu, že nájde ng
        run: npx ng build --configuration production

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FITMIND_DBA6A }}'
          channelId: live
          projectId: fitmind-dba6a
          entryPoint: ./FitMind
